-- lib_configuration --
INSERT INTO lib_configuration(ID, NAME_LIB, HOST_LIB, PORT, DBNAME, FORMAT_LIB, QUERY_TYPE, LOGIN, PWD, ENCODING)
  VALUES(1, 'Пушкинская библиотека', 'irbis.pushkinlibrary.kz', 210, 'ibis', 'RUSMARC', 'PREFIX_QUERY', NULL, NULL, 'UTF8')
GO

-- subindex --
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(1, 'RUSMARC', '100', 'a', 1, 0, 7)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(2, 'RUSMARC', '100', 'a', 2, 8, 8)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(3, 'RUSMARC', '100', 'a', 3, 9, 12)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(4, 'RUSMARC', '100', 'a', 4, 13, 16)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(5, 'RUSMARC', '100', 'a', 5, 17, 19)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(6, 'RUSMARC', '100', 'a', 6, 20, 20)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(7, 'RUSMARC', '100', 'a', 7, 21, 21)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(8, 'RUSMARC', '100', 'a', 8, 22, 24)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(9, 'RUSMARC', '100', 'a', 9, 25, 25)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(10, 'RUSMARC', '100', 'a', 10, 26, 29)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(11, 'RUSMARC', '100', 'a', 11, 30, 33)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(12, 'RUSMARC', '100', 'a', 12, 34, 35)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(13, 'RUSMARC', '105', 'a', 1, 0, 3)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(14, 'RUSMARC', '105', 'a', 2, 4, 7)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(15, 'RUSMARC', '105', 'a', 3, 8, 8)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(16, 'RUSMARC', '105', 'a', 4, 9, 9)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(17, 'RUSMARC', '105', 'a', 5, 10, 10)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(18, 'RUSMARC', '105', 'a', 6, 11, 11)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(19, 'RUSMARC', '105', 'a', 7, 12, 12)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(20, 'RUSMARC', '110', 'a', 1, 0, 0)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(21, 'RUSMARC', '110', 'a', 2, 1, 1)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(22, 'RUSMARC', '110', 'a', 3, 2, 2)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(23, 'RUSMARC', '110', 'a', 4, 3, 3)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(24, 'RUSMARC', '110', 'a', 5, 4, 6)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(25, 'RUSMARC', '110', 'a', 6, 7, 7)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(26, 'RUSMARC', '110', 'a', 7, 8, 8)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(27, 'RUSMARC', '110', 'a', 8, 9, 9)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(28, 'RUSMARC', '110', 'a', 9, 10, 10)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(29, 'RUSMARC', '115', 'a', 1, 0, 0)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(30, 'RUSMARC', '115', 'a', 2, 1, 3)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(31, 'RUSMARC', '115', 'a', 3, 4, 4)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(32, 'RUSMARC', '115', 'a', 4, 5, 5)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(33, 'RUSMARC', '115', 'a', 5, 6, 6)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(34, 'RUSMARC', '115', 'a', 6, 7, 7)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(35, 'RUSMARC', '115', 'a', 7, 8, 8)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(36, 'RUSMARC', '115', 'a', 8, 9, 9)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(37, 'RUSMARC', '115', 'a', 9, 10, 10)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(38, 'RUSMARC', '115', 'a', 10, 11, 14)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(39, 'RUSMARC', '115', 'a', 11, 15, 15)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(40, 'RUSMARC', '115', 'a', 12, 16, 16)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(41, 'RUSMARC', '115', 'a', 13, 17, 17)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(42, 'RUSMARC', '115', 'a', 14, 18, 18)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(43, 'RUSMARC', '115', 'a', 15, 19, 19)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(44, 'RUSMARC', '115', 'b', 1, 0, 0)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(45, 'RUSMARC', '115', 'b', 2, 1, 1)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(46, 'RUSMARC', '115', 'b', 3, 2, 2)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(47, 'RUSMARC', '115', 'b', 4, 3, 3)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(48, 'RUSMARC', '115', 'b', 5, 4, 4)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(49, 'RUSMARC', '115', 'b', 6, 5, 5)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(50, 'RUSMARC', '115', 'b', 7, 6, 6)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(51, 'RUSMARC', '115', 'b', 8, 7, 7)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(52, 'RUSMARC', '115', 'b', 9, 8, 8)
GO
INSERT INTO subindex(ID, FORMAT_LIB, FIELD, TAG, SUBINDEX, START, END)
  VALUES(53, 'RUSMARC', '115', 'b', 10, 9, 14)
GO

